import { useState } from 'react';
import { Plus, Sparkles, Loader2, X, Image, Tag, DollarSign, FileText, Package, Lock } from 'lucide-react';
import { Button } from './ui/Button';
import { motion, AnimatePresence } from 'motion/react';

export default function AdminProductForm() {
  const [isOpen, setIsOpen] = useState(false);
  const [adminKey, setAdminKey] = useState('');
  const [form, setForm] = useState({
    name: '',
    description: '',
    price: '',
    image_url: '',
    category: 'general',
    features: '', // For AI generation context
  });
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [result, setResult] = useState<{ type: 'success' | 'error'; message: string } | null>(null);

  const categories = [
    { value: 'general', label: 'General' },
    { value: 'video-editing', label: 'Video Editing' },
    { value: 'subscriptions', label: 'Premium Subs' },
    { value: 'design', label: 'Graphic Design' },
    { value: 'vpn', label: 'VPN & Security' },
    { value: 'software', label: 'Software Keys' },
    { value: 'ai-tools', label: 'AI Tools' },
    { value: 'gaming', label: 'Gaming' },
    { value: 'courses', label: 'Online Courses' },
  ];

  function validate() {
    const e: Record<string, string> = {};
    if (!adminKey.trim()) e.adminKey = 'Admin key is required';
    if (!form.name.trim()) e.name = 'Product name is required';
    if (!form.price || Number(form.price) <= 0) e.price = 'Price must be greater than 0';
    setErrors(e);
    return Object.keys(e).length === 0;
  }

  // ✨ Magic Generate — calls Gemma proxy to auto-generate description
  async function handleMagicGenerate() {
    if (!form.name.trim()) {
      setErrors({ ...errors, name: 'Enter product name first to generate description' });
      return;
    }

    setGenerating(true);
    setResult(null);

    try {
      const res = await fetch('/api/gemma-proxy', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: form.name.trim(),
          features: form.features.trim() || undefined,
          category: form.category,
        }),
      });

      const data = await res.json();

      if (data.success && data.description) {
        setForm({ ...form, description: data.description });
        setResult({ type: 'success', message: 'Description generated by AI ✨' });
      } else {
        setResult({ type: 'error', message: data.error || 'Failed to generate description' });
      }
    } catch {
      setResult({ type: 'error', message: 'Could not connect to AI service' });
    } finally {
      setGenerating(false);
    }
  }

  // Submit product to /api/admin/add
  async function handleSubmit() {
    if (!validate()) return;

    setSubmitting(true);
    setResult(null);

    try {
      const res = await fetch('/api/admin/add', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-admin-key': adminKey.trim(),
        },
        body: JSON.stringify({
          name: form.name.trim(),
          description: form.description.trim(),
          price: Number(form.price),
          image_url: form.image_url.trim(),
          category: form.category,
        }),
      });

      const data = await res.json();

      if (data.success) {
        setResult({ type: 'success', message: `Product added! ID: #${data.productId}` });
        setForm({ name: '', description: '', price: '', image_url: '', category: 'general', features: '' });
      } else {
        setResult({ type: 'error', message: data.error || 'Failed to add product' });
      }
    } catch {
      setResult({ type: 'error', message: 'Could not connect to the server' });
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <>
      {/* Floating Admin Button — bottom-right corner */}
      <button
        onClick={() => setIsOpen(true)}
        className="fixed bottom-6 right-6 z-40 w-14 h-14 rounded-full bg-gray-900 text-white shadow-xl hover:bg-gray-800 flex items-center justify-center transition-all hover:scale-110"
        title="Admin: Add Product"
      >
        <Plus size={24} />
      </button>

      {/* Admin Drawer */}
      <AnimatePresence>
        {isOpen && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 bg-black/50 z-50"
              onClick={() => setIsOpen(false)}
            />

            <motion.div
              initial={{ x: '100%' }}
              animate={{ x: 0 }}
              exit={{ x: '100%' }}
              transition={{ type: 'spring', damping: 30, stiffness: 300 }}
              className="fixed right-0 top-0 bottom-0 w-full max-w-lg z-50 bg-white shadow-xl flex flex-col"
            >
              {/* Header */}
              <div className="flex items-center justify-between p-4 border-b border-gray-100">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-lg bg-gray-900 flex items-center justify-center">
                    <Package size={16} className="text-white" />
                  </div>
                  <div>
                    <h2 className="text-lg font-bold">Add Product</h2>
                    <p className="text-xs text-gray-400">Admin Panel</p>
                  </div>
                </div>
                <Button variant="ghost" size="icon" onClick={() => setIsOpen(false)}>
                  <X size={20} />
                </Button>
              </div>

              {/* Form */}
              <div className="flex-1 overflow-y-auto p-5 space-y-4">
                {/* Admin Key */}
                <div>
                  <label className="flex items-center gap-1.5 text-sm font-medium text-gray-700 mb-1.5">
                    <Lock size={14} /> Admin Secret Key
                  </label>
                  <input
                    type="password"
                    value={adminKey}
                    onChange={(e) => setAdminKey(e.target.value)}
                    placeholder="Enter admin secret key"
                    className={`w-full px-3 py-2.5 rounded-lg border ${errors.adminKey ? 'border-red-400' : 'border-gray-200'} focus:border-gray-900 focus:outline-none focus:ring-2 focus:ring-gray-900/20 text-sm`}
                  />
                  {errors.adminKey && <p className="text-red-500 text-xs mt-1">{errors.adminKey}</p>}
                </div>

                <hr className="border-gray-100" />

                {/* Product Name */}
                <div>
                  <label className="flex items-center gap-1.5 text-sm font-medium text-gray-700 mb-1.5">
                    <Tag size={14} /> Product Name
                  </label>
                  <input
                    type="text"
                    value={form.name}
                    onChange={(e) => setForm({ ...form, name: e.target.value })}
                    placeholder="e.g. Netflix Premium 4K - 1 Month"
                    className={`w-full px-3 py-2.5 rounded-lg border ${errors.name ? 'border-red-400' : 'border-gray-200'} focus:border-gray-900 focus:outline-none focus:ring-2 focus:ring-gray-900/20 text-sm`}
                  />
                  {errors.name && <p className="text-red-500 text-xs mt-1">{errors.name}</p>}
                </div>

                {/* Category */}
                <div>
                  <label className="flex items-center gap-1.5 text-sm font-medium text-gray-700 mb-1.5">
                    <FileText size={14} /> Category
                  </label>
                  <select
                    value={form.category}
                    onChange={(e) => setForm({ ...form, category: e.target.value })}
                    className="w-full px-3 py-2.5 rounded-lg border border-gray-200 focus:border-gray-900 focus:outline-none focus:ring-2 focus:ring-gray-900/20 text-sm bg-white"
                  >
                    {categories.map((cat) => (
                      <option key={cat.value} value={cat.value}>{cat.label}</option>
                    ))}
                  </select>
                </div>

                {/* Key Features (for AI context) */}
                <div>
                  <label className="flex items-center gap-1.5 text-sm font-medium text-gray-700 mb-1.5">
                    <Sparkles size={14} className="text-purple-500" /> Key Features
                    <span className="text-gray-400 font-normal">(optional, helps AI)</span>
                  </label>
                  <input
                    type="text"
                    value={form.features}
                    onChange={(e) => setForm({ ...form, features: e.target.value })}
                    placeholder="e.g. 4K UHD, 4 screens, no ads, global access"
                    className="w-full px-3 py-2.5 rounded-lg border border-gray-200 focus:border-gray-900 focus:outline-none focus:ring-2 focus:ring-gray-900/20 text-sm"
                  />
                </div>

                {/* Description + Magic Generate */}
                <div>
                  <div className="flex items-center justify-between mb-1.5">
                    <label className="flex items-center gap-1.5 text-sm font-medium text-gray-700">
                      <FileText size={14} /> Description
                    </label>
                    <button
                      onClick={handleMagicGenerate}
                      disabled={generating}
                      className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-gradient-to-r from-purple-500 to-pink-500 text-white text-xs font-semibold hover:from-purple-600 hover:to-pink-600 transition-all disabled:opacity-50 shadow-sm"
                    >
                      {generating ? (
                        <>
                          <Loader2 size={12} className="animate-spin" /> Generating...
                        </>
                      ) : (
                        <>
                          <Sparkles size={12} /> Magic Generate
                        </>
                      )}
                    </button>
                  </div>
                  <textarea
                    value={form.description}
                    onChange={(e) => setForm({ ...form, description: e.target.value })}
                    placeholder="Product description (or click Magic Generate ✨)"
                    rows={4}
                    className="w-full px-3 py-2.5 rounded-lg border border-gray-200 focus:border-gray-900 focus:outline-none focus:ring-2 focus:ring-gray-900/20 text-sm resize-none"
                  />
                </div>

                {/* Price */}
                <div>
                  <label className="flex items-center gap-1.5 text-sm font-medium text-gray-700 mb-1.5">
                    <DollarSign size={14} /> Price (৳ BDT)
                  </label>
                  <input
                    type="number"
                    value={form.price}
                    onChange={(e) => setForm({ ...form, price: e.target.value })}
                    placeholder="0"
                    min="1"
                    className={`w-full px-3 py-2.5 rounded-lg border ${errors.price ? 'border-red-400' : 'border-gray-200'} focus:border-gray-900 focus:outline-none focus:ring-2 focus:ring-gray-900/20 text-sm`}
                  />
                  {errors.price && <p className="text-red-500 text-xs mt-1">{errors.price}</p>}
                </div>

                {/* Image URL */}
                <div>
                  <label className="flex items-center gap-1.5 text-sm font-medium text-gray-700 mb-1.5">
                    <Image size={14} /> Image URL
                    <span className="text-gray-400 font-normal">(optional)</span>
                  </label>
                  <input
                    type="url"
                    value={form.image_url}
                    onChange={(e) => setForm({ ...form, image_url: e.target.value })}
                    placeholder="https://example.com/product-image.jpg"
                    className="w-full px-3 py-2.5 rounded-lg border border-gray-200 focus:border-gray-900 focus:outline-none focus:ring-2 focus:ring-gray-900/20 text-sm"
                  />
                </div>

                {/* Result message */}
                {result && (
                  <motion.div
                    initial={{ opacity: 0, y: -8 }}
                    animate={{ opacity: 1, y: 0 }}
                    className={`p-3 rounded-lg text-sm font-medium ${
                      result.type === 'success'
                        ? 'bg-green-50 border border-green-200 text-green-700'
                        : 'bg-red-50 border border-red-200 text-red-600'
                    }`}
                  >
                    {result.message}
                  </motion.div>
                )}
              </div>

              {/* Footer */}
              <div className="p-5 border-t border-gray-100">
                <Button
                  className="w-full bg-gray-900 hover:bg-gray-800"
                  isLoading={submitting}
                  onClick={handleSubmit}
                >
                  <Plus size={16} className="mr-2" />
                  Add Product to Store
                </Button>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </>
  );
}
